onbloc/adena-wallet

package.json
public/manifest.json
src/background.ts
src/inject.ts
src/popup.tsx
src/router/CustomRouter.tsx
src/router/path.ts
src/services/client/fetcher.ts
src/services/lcd.ts
src/services/tx_utils.ts
src/ui/common/Button/HamburgerMenuBtn.tsx
src/ui/common/Copy.tsx
src/ui/common/Header/Header.tsx
src/ui/common/Menu/DrawerMenu/DrawerMenu.tsx
src/ui/common/Menu/TopMenu/TopMenu.tsx
src/ui/domains/Login/useLogin.ts
src/ui/domains/Wallet/ApproveTransaction/ApproveTransactionView.tsx
src/ui/domains/Wallet/WalletCreate/WalletCreateView.tsx

modified:   package.json
modified:   public/manifest.json
modified:   src/background.ts
modified:   src/inject.ts
modified:   src/popup.tsx
modified:   src/router/CustomRouter.tsx
modified:   src/router/path.ts
modified:   src/services/client/fetcher.ts
modified:   src/services/lcd.ts
modified:   src/services/tx_utils.ts
modified:   src/ui/common/Button/HamburgerMenuBtn.tsx
modified:   src/ui/common/Copy.tsx
modified:   src/ui/common/Header/Header.tsx
modified:   src/ui/common/Menu/DrawerMenu/DrawerMenu.tsx
modified:   src/ui/common/Menu/TopMenu/TopMenu.tsx
modified:   src/ui/domains/Login/useLogin.ts
modified:   src/ui/domains/Wallet/ApproveTransaction/ApproveTransactionView.tsx
modified:   src/ui/domains/Wallet/WalletCreate/WalletCreateView.tsx

Version 1.3.1

---

packages/adena-extension/src/hooks/use-wallet-loader.tsx

Added logic to verify the existence of the wallet when loading the wallet.

fix: validate wallet

---

.circleci/config.yml

Run npm test during build
Will help catch errors :)
TODO: Make tests (in future PR)

Add npm test to circleci job

---

packages/adena-extension/src/common/utils/client-utils.ts

Fix url parse parameters

---

packages/adena-extension/src/assets/main-manage-tokens-filter.svg
packages/adena-extension/src/components/main/main-manage-token-button/main-manage-token-button.spec.tsx
packages/adena-extension/src/components/main/main-manage-token-button/main-manage-token-button.stories.tsx
packages/adena-extension/src/components/main/main-manage-token-button/main-manage-token-button.styles.ts
packages/adena-extension/src/components/main/main-manage-token-button/main-manage-token-button.tsx

Create a Manage Tokens Button Component.

feat: [ADN-20] Create a manage tokens button component

---

packages/adena-extension/src/components/common/toggle/toggle.spec.tsx
packages/adena-extension/src/components/common/toggle/toggle.stories.tsx
packages/adena-extension/src/components/common/toggle/toggle.styles.ts
packages/adena-extension/src/components/common/toggle/toggle.tsx
packages/adena-extension/src/components/manage-token/manage-token-list-item-balance/manage-token-list-item-balance.spec.tsx
packages/adena-extension/src/components/manage-token/manage-token-list-item-balance/manage-token-list-item-balance.stories.tsx
packages/adena-extension/src/components/manage-token/manage-token-list-item-balance/manage-token-list-item-balance.tsx
packages/adena-extension/src/components/manage-token/manage-token-list-item/manage-token-list-item.spec.tsx
packages/adena-extension/src/components/manage-token/manage-token-list-item/manage-token-list-item.stories.tsx
packages/adena-extension/src/components/manage-token/manage-token-list-item/manage-token-list-item.styles.ts
packages/adena-extension/src/components/manage-token/manage-token-list-item/manage-token-list-item.tsx
packages/adena-extension/src/components/manage-token/manage-token-list/manage-token-list.spec.tsx
packages/adena-extension/src/components/manage-token/manage-token-list/manage-token-list.stories.tsx
packages/adena-extension/src/components/manage-token/manage-token-list/manage-token-list.styles.ts
packages/adena-extension/src/components/manage-token/manage-token-list/manage-token-list.tsx

Create the Manage Token page token list component.
[Component]
- common/toggle
- manage-token/manage-token-list
- manage-token/manage-token-list-item
- manage-token/manage-token-list-item-balance

feat: [ADN-35] Create the Manage Token page token list component

---

packages/adena-extension/src/assets/manage-token-added.svg
packages/adena-extension/src/assets/manage-token-search.svg
packages/adena-extension/src/components/manage-token/manage-token-search-input/manage-token-search-input.spec.tsx
packages/adena-extension/src/components/manage-token/manage-token-search-input/manage-token-search-input.stories.tsx
packages/adena-extension/src/components/manage-token/manage-token-search-input/manage-token-search-input.styles.ts
packages/adena-extension/src/components/manage-token/manage-token-search-input/manage-token-search-input.tsx

The token search component used on the manage token page.

feat: [ADN-22] Create a token search component

---

packages/adena-extension/src/assets/common-arrow-down-gray.svg
packages/adena-extension/src/assets/common-arrow-up-gray.svg
packages/adena-extension/src/assets/common-search.svg
packages/adena-extension/src/components/common/search-input/search-input.spec.tsx
packages/adena-extension/src/components/common/search-input/search-input.stories.tsx
packages/adena-extension/src/components/common/search-input/search-input.styles.ts
packages/adena-extension/src/components/common/search-input/search-input.tsx
packages/adena-extension/src/components/manage-token/additional-token-info/additional-token-info.spec.tsx
packages/adena-extension/src/components/manage-token/additional-token-info/additional-token-info.stories.tsx
packages/adena-extension/src/components/manage-token/additional-token-info/additional-token-info.styles.ts
packages/adena-extension/src/components/manage-token/additional-token-info/additional-token-info.tsx
packages/adena-extension/src/components/manage-token/additional-token-search-list/additional-token-search-list.spec.tsx
packages/adena-extension/src/components/manage-token/additional-token-search-list/additional-token-search-list.stories.tsx
packages/adena-extension/src/components/manage-token/additional-token-search-list/additional-token-search-list.styles.ts
packages/adena-extension/src/components/manage-token/additional-token-search-list/additional-token-search-list.tsx
packages/adena-extension/src/components/manage-token/additional-token-select-box/additional-token-select-box.spec.tsx
packages/adena-extension/src/components/manage-token/additional-token-select-box/additional-token-select-box.stories.tsx
packages/adena-extension/src/components/manage-token/additional-token-select-box/additional-token-select-box.styles.ts
packages/adena-extension/src/components/manage-token/additional-token-select-box/additional-token-select-box.tsx
packages/adena-extension/src/components/manage-token/additional-token/additional-token.spec.tsx
packages/adena-extension/src/components/manage-token/additional-token/additional-token.stories.tsx
packages/adena-extension/src/components/manage-token/additional-token/additional-token.styles.ts
packages/adena-extension/src/components/manage-token/additional-token/additional-token.tsx

A component that searches for and adds tokens to manage.

feat: [ADN-42] Create an additional token search component

---

packages/adena-extension/src/components/common/sub-header/sub-header.spec.tsx
packages/adena-extension/src/components/common/sub-header/sub-header.stories.tsx
packages/adena-extension/src/components/common/sub-header/sub-header.styles.ts
packages/adena-extension/src/components/common/sub-header/sub-header.tsx

Create a common child header component within the page.

feat: [ADN-44] Create a Sub Header Component

---

packages/adena-extension/src/components/transfer/balance-input/balance-input.spec.tsx
packages/adena-extension/src/components/transfer/balance-input/balance-input.stories.tsx
packages/adena-extension/src/components/transfer/balance-input/balance-input.styles.ts
packages/adena-extension/src/components/transfer/balance-input/balance-input.tsx

Used on the token transfer page.

feat: [ADN-49] Create a token transfer balance input component

---

packages/adena-extension/src/components/transaction-history/transaction-history-list-item/transaction-history-list-item.spec.tsx
packages/adena-extension/src/components/transaction-history/transaction-history-list-item/transaction-history-list-item.stories.tsx
packages/adena-extension/src/components/transaction-history/transaction-history-list-item/transaction-history-list-item.styles.ts
packages/adena-extension/src/components/transaction-history/transaction-history-list-item/transaction-history-list-item.tsx
packages/adena-extension/src/components/transaction-history/transaction-history-list/transaction-history-list.spec.tsx
packages/adena-extension/src/components/transaction-history/transaction-history-list/transaction-history-list.stories.tsx
packages/adena-extension/src/components/transaction-history/transaction-history-list/transaction-history-list.styles.ts
packages/adena-extension/src/components/transaction-history/transaction-history-list/transaction-history-list.tsx
packages/adena-extension/src/components/transaction-history/transaction-history/transaction-history.spec.tsx
packages/adena-extension/src/components/transaction-history/transaction-history/transaction-history.stories.tsx
packages/adena-extension/src/components/transaction-history/transaction-history/transaction-history.styles.ts
packages/adena-extension/src/components/transaction-history/transaction-history/transaction-history.tsx

This is the component used on the transaction history page.

feat: [ADN-24] Create the transaction history component

---

packages/adena-extension/src/assets/transfer-address-book.svg
packages/adena-extension/src/components/transfer/address-book-list/address-book-list.spec.tsx
packages/adena-extension/src/components/transfer/address-book-list/address-book-list.stories.tsx
packages/adena-extension/src/components/transfer/address-book-list/address-book-list.styles.ts
packages/adena-extension/src/components/transfer/address-book-list/address-book-list.tsx
packages/adena-extension/src/components/transfer/address-input/address-input.spec.tsx
packages/adena-extension/src/components/transfer/address-input/address-input.stories.tsx
packages/adena-extension/src/components/transfer/address-input/address-input.styles.ts
packages/adena-extension/src/components/transfer/address-input/address-input.tsx

Create a token transfer address input component.

feat: [ADN-48] Create a token transfer address input component

---

packages/adena-extension/src/assets/transfer-arrow-down.svg
packages/adena-extension/src/components/transfer/transfer-summary-address/transfer-summary-address.spec.tsx
packages/adena-extension/src/components/transfer/transfer-summary-address/transfer-summary-address.stories.tsx
packages/adena-extension/src/components/transfer/transfer-summary-address/transfer-summary-address.styles.ts
packages/adena-extension/src/components/transfer/transfer-summary-address/transfer-summary-address.tsx
packages/adena-extension/src/components/transfer/transfer-summary-balance/transfer-summary-balance.spec.tsx
packages/adena-extension/src/components/transfer/transfer-summary-balance/transfer-summary-balance.stories.tsx
packages/adena-extension/src/components/transfer/transfer-summary-balance/transfer-summary-balance.styles.ts
packages/adena-extension/src/components/transfer/transfer-summary-balance/transfer-summary-balance.tsx
packages/adena-extension/src/components/transfer/transfer-summary-network-fee/transfer-summary-network-fee.spec.tsx
packages/adena-extension/src/components/transfer/transfer-summary-network-fee/transfer-summary-network-fee.stories.tsx
packages/adena-extension/src/components/transfer/transfer-summary-network-fee/transfer-summary-network-fee.styles.ts
packages/adena-extension/src/components/transfer/transfer-summary-network-fee/transfer-summary-network-fee.tsx
packages/adena-extension/src/components/transfer/transfer-summary/transfer-summary.spec.tsx
packages/adena-extension/src/components/transfer/transfer-summary/transfer-summary.stories.tsx
packages/adena-extension/src/components/transfer/transfer-summary/transfer-summary.styles.ts
packages/adena-extension/src/components/transfer/transfer-summary/transfer-summary.tsx

This component is used on the transfer token summary page.

feat: [ADN-47] Create a transfer token summary component

---

packages/adena-extension/src/common/provider/adena/adena-provider.tsx
packages/adena-extension/src/common/utils/client-utils.ts
packages/adena-extension/src/components/transaction-history/transaction-history-list/transaction-history-list.spec.tsx
packages/adena-extension/src/components/transaction-history/transaction-history-list/transaction-history-list.stories.tsx
packages/adena-extension/src/components/transaction-history/transaction-history-list/transaction-history-list.tsx
packages/adena-extension/src/components/transaction-history/transaction-history/transaction-history.spec.tsx
packages/adena-extension/src/components/transaction-history/transaction-history/transaction-history.stories.tsx
packages/adena-extension/src/components/transaction-history/transaction-history/transaction-history.tsx
packages/adena-extension/src/containers/history-container/history-container.tsx
packages/adena-extension/src/hooks/use-current-account.tsx
packages/adena-extension/src/layouts/history-layout/history-layout.styles.ts
packages/adena-extension/src/layouts/history-layout/history-layout.tsx
packages/adena-extension/src/pages/wallet/history/index.tsx
packages/adena-extension/src/pages/wallet/transaction-detail/index.tsx
packages/adena-extension/src/repositories/transaction/index.ts
packages/adena-extension/src/repositories/transaction/mapper/transaction-history-mapper.ts
packages/adena-extension/src/repositories/transaction/response/transaction-history-response.ts
packages/adena-extension/src/repositories/transaction/transaction-history.ts
packages/adena-extension/src/services/transaction/index.ts
packages/adena-extension/src/services/transaction/transaction-history.ts

Changed the page showing the list of transactions.
Changed the endpoint to the Adena API under development.

feat: [ADN-27] Implement the transaction history page

---

packages/adena-extension/src/common/provider/adena/adena-provider.tsx
packages/adena-extension/src/components/transfer/balance-input/balance-input.tsx
packages/adena-extension/src/containers/transfer-input-container/transfer-input-container.tsx
packages/adena-extension/src/containers/transfer-summary-container/transfer-summary-container.tsx
packages/adena-extension/src/hooks/use-adderss-book-input.ts
packages/adena-extension/src/hooks/use-balance-input.ts
packages/adena-extension/src/hooks/use-token-balance.ts
packages/adena-extension/src/inject/message/methods/core.ts
packages/adena-extension/src/pages/wallet/search/index.tsx
packages/adena-extension/src/repositories/common/chain.ts
packages/adena-extension/src/repositories/common/mapper/network-metainfo-mapper.ts
packages/adena-extension/src/repositories/wallet/wallet-address.ts
packages/adena-extension/src/services/resource/chain.ts
packages/adena-extension/src/services/transaction/transaction.ts
packages/adena-extension/src/services/wallet/wallet-address-book.ts
packages/adena-extension/src/services/wallet/wallet-balance.ts

Implemented the page logic for the token transfer page.
Implemented GRC20 and native token transfer functions for each token type.

feat: [ADN-53] Implement GRC20 token transfer function

---

packages/adena-extension/src/containers/transfer-summary-container/transfer-summary-container.tsx
packages/adena-extension/src/pages/wallet/approve-sign/index.tsx
packages/adena-extension/src/pages/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/pages/wallet/send-confirm/index.tsx
packages/adena-extension/src/services/transaction/transaction.ts
packages/adena-module/src/transaction/transaction.ts
packages/adena-module/src/wallet/wallet.ts

Changed the way transactions are created and sent.
- document
- signature
- transaction
- send

feat: [ADN-2] Change the transaction signing module

---

packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/components/background/background.tsx
packages/adena-extension/src/hooks/use-add-account.tsx
packages/adena-extension/src/hooks/use-current-account.tsx
packages/adena-extension/src/hooks/use-import-account.tsx
packages/adena-extension/src/hooks/use-remove-account.tsx
packages/adena-extension/src/layouts/sub-menu/index.tsx
packages/adena-extension/src/pages/certify/import-private-key/index.tsx
packages/adena-module/src/wallet/wallet.ts

Resolve errors that occur when modifying wallet account data.

fix: [ADN-57] Fix account addition errors

---

packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/components/loading-screen/loading-main.tsx
packages/adena-extension/src/hooks/use-gno-client.tsx
packages/adena-extension/src/hooks/use-network.ts
packages/adena-extension/src/hooks/use-token-balance.ts
packages/adena-extension/src/pages/certify/change-network/index.tsx
packages/adena-extension/src/pages/wallet/approve-sign/index.tsx
packages/adena-extension/src/pages/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/states/balance.ts

Fix errors when changing networks.

fix: [ADN-58] Infinite loading on network changes

---

packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/components/background/background.tsx
packages/adena-extension/src/components/loading-screen/loading-main.tsx
packages/adena-extension/src/hooks/use-clear.tsx
packages/adena-extension/src/layouts/error-container/error-container.tsx
packages/adena-extension/src/pages/certify/change-network/index.tsx
packages/adena-extension/src/pages/certify/launch-adena/index.tsx
packages/adena-extension/src/services/resource/chain.ts
packages/adena-extension/src/states/common.ts

Fixed infinite loading when changing the network setting to local.

fix: [ADN-97] Fix an infinite loading error

---

packages/adena-extension/src/components/background/background.tsx
packages/adena-extension/src/hooks/use-scroll-history.tsx

Resets the scroll position to the top when paging.

fix: [ADN-169] Fix a scrolling error

---

packages/adena-extension/src/pages/certify/login/index.tsx
packages/adena-extension/src/pages/wallet/approve-login/index.tsx

Sets the input item to focus as a condition for the screen to render.

feat: Make the main page typable

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json
packages/adena-module/src/wallet/wallet.ts
packages/gno-client/package.json

- Fix a sending error for imported account

Release Adena version '1.6.2'

---

packages/adena-extension/custom.d.ts
packages/adena-extension/src/common/constants/event-key.constant.ts
packages/adena-extension/src/content.ts
packages/adena-extension/src/global.d.ts
packages/adena-extension/src/hooks/use-current-account.tsx
packages/adena-extension/src/hooks/use-event.tsx
packages/adena-extension/src/inject.ts
packages/adena-extension/src/inject/message/event-message.ts
packages/adena-extension/src/inject/message/index.ts
packages/adena-extension/tsconfig.json

Added an event listener that fires when an account is changed.

feat: [ADN-37] Add an event listener in Account Change

---

packages/adena-extension/package.json
packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/hooks/use-add-account.tsx
packages/adena-extension/src/hooks/use-token-balance.ts
packages/adena-extension/src/pages/certify/add-account-page/AddAccountPage.styles.ts
packages/adena-extension/src/pages/certify/add-account-page/AddAccountPage.tsx
packages/adena-extension/src/pages/certify/approve-connect-hardware-wallet/finish/finish.tsx
packages/adena-extension/src/pages/certify/your-seed-phrase/index.tsx
packages/adena-extension/src/router/custom-router.tsx
packages/adena-module/src/wallet/account/ledger-account.ts
packages/adena-module/src/wallet/account/seed-account.ts
packages/adena-module/src/wallet/account/single-account.ts
packages/adena-module/src/wallet/wallet.ts
yarn.lock

- Use gno-js-client to get the address used for GNOT and GRC20 balance queries.

feat: [ADN-41] Integrate gno-js-client library.

---

packages/adena-extension/src/common/storage/chrome-local-storage.ts
packages/adena-extension/src/pages/certify/enter-seed/use-enter-seed.ts
packages/adena-extension/src/services/resource/token.ts

feat: [ADN-164] Change the route of sourcing static token data from gno-token-resource

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-extension/src/common/provider/gno/gno-provider.ts
packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/common/utils/client-utils.ts
packages/adena-extension/src/components/background/background.tsx
packages/adena-extension/src/containers/approve-establish-container/approve-establish-container.tsx
packages/adena-extension/src/containers/approve-transaction-container/approve-transaction-container.tsx
packages/adena-extension/src/pages/certify/change-network/index.tsx
packages/adena-extension/src/services/wallet/wallet-account.ts
packages/adena-module/package.json
packages/adena-module/src/amino/signdoc.ts
packages/adena-module/src/wallet/wallet-sign.spec.ts

- Modify GetAccount function response value
- Fix custom network connection bug
- Fix a HTMLEscape bug in injection API

Release Adena version '1.7.4'

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- Change description
- Modify the transaction details page

Release Adena version 'v1.7.6'

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-extension/src/pages/wallet/transaction-detail/index.tsx
packages/adena-extension/src/pages/wallet/transaction-detail/use-status.ts
packages/adena-module/package.json

- Change the transaction detail page URI

Release Adena version 'v1.7.7'

---

packages/adena-extension/src/hooks/web/setup-airgap/use-setup-airgap-screen.ts

fix: Fix to allow existing private key accounts to be registered as airgap accounts

---

packages/adena-extension/src/components/atoms/datatable/index.tsx
packages/adena-extension/src/components/molecules/approve-ledger-loading/approve-ledger-loading.spec.tsx
packages/adena-extension/src/components/molecules/approve-ledger-loading/approve-ledger-loading.stories.tsx
packages/adena-extension/src/components/molecules/approve-ledger-loading/approve-ledger-loading.styles.ts
packages/adena-extension/src/components/molecules/approve-ledger-loading/index.tsx
packages/adena-extension/src/components/pages/transfer-ledger-loading/transfer-ledger-loading.spec.tsx
packages/adena-extension/src/components/pages/transfer-ledger-loading/transfer-ledger-loading.stories.tsx
packages/adena-extension/src/components/pages/transfer-ledger-loading/transfer-ledger-loading.styles.ts
packages/adena-extension/src/components/pages/transfer-ledger-loading/transfer-ledger-loading.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign-ledger-loading/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign-transaction-ledger-loading/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-ledger-loading/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-ledger-loading/index.tsx
packages/adena-extension/src/pages/web/create-password-screen/index.tsx
packages/adena-extension/src/pages/web/wallet-export-screen/result.tsx

- feature
- Highlight the link to the Terms page on the password creation page
- Display what the device sees when signing transactions for a Ledger account 
- Remove unnecessary areas from the key export results page
- Related issues: 
- Adena Security Evaluation Feb 2024 - INFO-003
- Adena Security Evaluation Feb 2024 - INFO-004

feat: Improve minor web UI

---

packages/adena-extension/src/common/constants/ui.constant.ts
packages/adena-extension/src/components/atoms/web-main/index.tsx
packages/adena-extension/src/pages/web/account-add-screen/index.tsx
packages/adena-extension/src/pages/web/account-import-screen/index.tsx
packages/adena-extension/src/pages/web/advanced-option-screen/index.tsx
packages/adena-extension/src/pages/web/connect-ledger/connect-screen/index.tsx
packages/adena-extension/src/pages/web/create-password-screen/index.tsx
packages/adena-extension/src/pages/web/google-login-screen/index.tsx
packages/adena-extension/src/pages/web/questionnaire-screen/index.tsx
packages/adena-extension/src/pages/web/select-hard-wallet-screen/index.tsx
packages/adena-extension/src/pages/web/setup-airgap-screen/index.tsx
packages/adena-extension/src/pages/web/wallet-create-screen/index.tsx
packages/adena-extension/src/pages/web/wallet-import-screen/index.tsx

- style
- Adjust the top spacing of the extension web page
- Add a responsive height

fix: Fix spacing on some pages to be responsive

---

packages/adena-extension/src/common/provider/adena/adena-provider.tsx
packages/adena-extension/src/hooks/use-address-book.tsx
packages/adena-extension/src/hooks/use-clear.tsx
packages/adena-extension/src/hooks/use-init-wallet.tsx
packages/adena-extension/src/inject/message/methods/core.ts
packages/adena-extension/src/migrates/migrations/v005/storage-migration-v005.spec.ts
packages/adena-extension/src/migrates/migrations/v005/storage-migration-v005.ts
packages/adena-extension/src/migrates/migrations/v005/storage-model-v005.ts
packages/adena-extension/src/migrates/storage-migrator.spec.ts
packages/adena-extension/src/pages/popup/certify/add-address/index.tsx
packages/adena-extension/src/pages/popup/certify/address-book/index.tsx
packages/adena-extension/src/pages/popup/certify/address-book/loading-address-book.tsx
packages/adena-extension/src/repositories/wallet/wallet-address.ts
packages/adena-extension/src/services/wallet/wallet-address-book.ts
packages/adena-extension/src/states/wallet.tsx

- feature
- Encrypts address books that are stored in plain text in Storage.
- Adds a loading screen from the address book screen due to encryption.
- Resolves:
- Adena Security Evaluation Feb 2024 - LOW-002

feat: Encrypt address book data

---

packages/adena-extension/package.json
yarn.lock

- chore
- Add "zxcvbn" types dependency

chore: Add types dependency

---

packages/adena-extension/src/pages/web/wallet-import-screen/index.tsx

- bug
- Resolve rendering errors after entering a mnemonic on the wallet import page

fix: Fix a render issue

---

packages/adena-extension/src/common/utils/password-utils.ts

- feature
- Change password complexity criteria to be more stringent

feat: Change password complexity criteria to be more stringent

---

packages/adena-extension/src/components/atoms/web-main/index.tsx
packages/adena-extension/src/components/pages/transfer-ledger-loading/transfer-ledger-loading.styles.ts
packages/adena-extension/src/pages/popup/wallet/transfer-ledger-loading/index.tsx

- bug
- Change the conditions of the media query on the extension's web page

fix: Fix minor UI issues

---

.yarnrc.yml

- chore
- Change yarn's telemetry options

chore: Fix invalid telemetry options in yarn

---

packages/adena-extension/src/pages/popup/certify/login/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-login/index.tsx

- bug
- Change the login page to not check for password complexity

fix: Fix password verification on the login

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Change to package version 1.9.1

chore: Change to package version 1.9.1

---

packages/adena-extension/src/pages/popup/certify/change-password/index.tsx

- style
- Remove the margin of the error message on the Change password page

fix: Fix minor UI issues on the change password page

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update package version of Adena Wallet to 1.9.2

chore: Change to package version 1.9.2

---

packages/adena-extension/src/components/pages/additional-token/additional-token-search-list/additional-token-search-list.tsx
packages/adena-extension/src/components/pages/additional-token/additional-token-select-box/additional-token-select-box.spec.tsx
packages/adena-extension/src/components/pages/additional-token/additional-token-select-box/additional-token-select-box.stories.tsx
packages/adena-extension/src/components/pages/additional-token/additional-token-select-box/additional-token-select-box.styles.ts
packages/adena-extension/src/components/pages/additional-token/additional-token-select-box/additional-token-select-box.tsx
packages/adena-extension/src/components/pages/additional-token/additional-token/index.tsx
packages/adena-extension/src/pages/popup/wallet/manage-token-added/index.tsx
packages/adena-extension/src/types/token.ts

- bug
- Fix UI breaks when token name and symbol are long on the Add custom GRC20 token page.

fix: Fix grc20 token search info

---

packages/adena-extension/src/components/atoms/highlight-number/highlight-number.styles.ts
packages/adena-extension/src/components/atoms/highlight-number/index.tsx
packages/adena-extension/src/components/molecules/token-balance/index.tsx
packages/adena-extension/src/components/molecules/token-balance/token-balance.styles.ts
packages/adena-extension/src/components/pages/main/main-network-label/main-network-label.spec.tsx
packages/adena-extension/src/components/pages/main/main-network-label/main-network-label.stories.tsx
packages/adena-extension/src/components/pages/main/main-network-label/main-network-label.styles.ts
packages/adena-extension/src/components/pages/main/main-network-label/main-network-label.tsx
packages/adena-extension/src/components/pages/main/main-token-balance/main-token-balance.styles.ts
packages/adena-extension/src/components/pages/main/main-token-balance/main-token-balance.tsx
packages/adena-extension/src/pages/popup/wallet/wallet-main/index.tsx
packages/adena-extension/src/styles/theme.ts

- feature
- The wallet main screen shows the current network.

feat: Add a network label

---

packages/adena-extension/src/components/pages/web/wallet-creation-help-overlay/wallet-creation-help-overlay.tsx
packages/adena-extension/src/pages/web/landing-screen/index.tsx

- refactor
- param 'init' is always true in the code
- use refetch function instead of updating a state

feat. refactor code

---

packages/adena-extension/src/components/molecules/approve-injection-loading/index.tsx

- feature
- Remove the 5-second timeout when sending transactions.

feat: Change timeout conditions when broadcasting transactions

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Change to package version 1.10.0

chore: Change to package version 1.10.0

---

packages/adena-extension/src/background.ts
packages/adena-extension/src/common/provider/adena/adena-provider.tsx
packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/hooks/use-balance-input.ts
packages/adena-extension/src/hooks/use-init-wallet.tsx
packages/adena-extension/src/hooks/use-token-balance.ts
packages/adena-extension/src/hooks/use-wallet.ts
packages/adena-extension/src/inject/message/methods/core.ts
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-input/index.tsx
packages/adena-extension/src/repositories/common/token.ts
packages/adena-extension/src/repositories/transaction/transaction-history.ts
packages/adena-extension/src/services/transaction/transaction-history.ts
packages/adena-extension/src/services/transaction/transaction.ts
packages/adena-extension/src/services/wallet/wallet-account.ts
packages/adena-extension/src/services/wallet/wallet-balance.ts
packages/adena-extension/src/services/wallet/wallet.ts

- fix
- Resolve initialization environment errors

fix: Initialize environment

---

packages/adena-extension/src/components/molecules/token-balance/index.tsx
packages/adena-extension/src/components/molecules/token-balance/token-balance.styles.ts
packages/adena-extension/src/components/pages/main/main-token-balance/main-token-balance.styles.ts
packages/adena-extension/src/components/pages/main/main-token-balance/main-token-balance.tsx

- feature
- Apply a responsive design to the component that shows the balance on the main screen.

feat: Improve balance display

---

packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.styles.ts

- style
- Fixed scroll area on injection popup.

fix: Fix incorrect scroll limit in injection

---

packages/adena-extension/src/hooks/use-network.ts
packages/adena-extension/src/router/popup/loading-main.tsx

- bug
- Change to initialize data for loading conditions when the network changes.

fix: Fix bugs when changing network

---

packages/adena-extension/src/App/popup.tsx

- bug
- Added an exception condition when the page first loads.

fix: Fix loading animation being displayed while locked

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Change to package version 1.10.1

chore: Change to package version 1.10.1

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Change to package version 1.10.2

chore: Change to package version 1.10.2

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.10.3.

chore: bump package version to 1.10.3

---

packages/adena-module/src/utils/messages-legacy.ts
packages/adena-module/src/wallet/keyring/keyring-util.ts

- fix
- Support for testnet3 network legacy modules.

fix: support for testnet3 network legacy modules

---

packages/adena-extension/src/resources/faucet/faucet-api.json

- chore
- Add the faucet API information to support Faucet on the test4 network.

chore: add faucet API to test4 network

---

packages/adena-extension/src/components/pages/router/side-menu-layout/side-menu-container.tsx
packages/adena-extension/src/components/pages/router/side-menu/side-menu.spec.tsx
packages/adena-extension/src/components/pages/router/side-menu/side-menu.tsx
packages/adena-extension/src/types/side-menu.ts

- fix
- Resolve rendering test case failures.

fix: resolve test case failures

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.11.0.

chore: bump package version to 1.11.0

---

packages/adena-extension/src/common/provider/adena/adena-provider.tsx
packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/common/utils/fetch-utils.ts
packages/adena-extension/src/common/utils/string-utils.ts
packages/adena-extension/src/components/pages/additional-token/additional-token-search-list/additional-token-search-list.tsx
packages/adena-extension/src/components/pages/additional-token/additional-token/index.tsx
packages/adena-extension/src/hooks/use-token-metainfo.tsx
packages/adena-extension/src/hooks/wallet/token-details/use-token-transactions-page.ts
packages/adena-extension/src/hooks/wallet/transaction-history/use-transaction-history-page.ts
packages/adena-extension/src/pages/popup/certify/change-network/index.tsx
packages/adena-extension/src/pages/popup/wallet/history/index.tsx
packages/adena-extension/src/pages/popup/wallet/manage-token-added/index.tsx
packages/adena-extension/src/pages/popup/wallet/token-details/index.tsx
packages/adena-extension/src/repositories/common/mapper/token-mapper.ts
packages/adena-extension/src/repositories/common/token.ts
packages/adena-extension/src/repositories/transaction/mapper/transaction-history-query.mapper.ts
packages/adena-extension/src/repositories/transaction/response/transaction-history-query-response.ts
packages/adena-extension/src/repositories/transaction/transaction-history.queries.ts
packages/adena-extension/src/repositories/transaction/transaction-history.ts
packages/adena-extension/src/services/resource/token.ts
packages/adena-extension/src/services/transaction/transaction-history.ts
packages/adena-extension/src/types/tx-history.ts

- feature
- Get a list of tokens via API from a network that supports the onbloc API.
- Modify tx-indexers that support pagination to use the pagination feature.

feat: modify tx-indexer response data

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.11.1.

chore: bump package version to 1.11.1

---

packages/adena-extension/package.json
packages/adena-extension/webpack.config.js
yarn.lock

- chore
- Resolve errors that prevent the PROCESS object from being read from an HTML page.

 chore: define process in webpack

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.11.2.

chore: bump package version to 1.11.2

---

packages/adena-extension/src/pages/popup/wallet/wallet-main/index.tsx

- fix
- Resolve an issue where the main page would intermittently fail to load the token image.

fix: load token image in main page

---

packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/components/atoms/button/index.tsx
packages/adena-extension/src/hooks/use-token-metainfo.tsx

- bug
- Remove invalid token initialize codes.

fix: remove initialize token image in provider

---

packages/adena-extension/src/assets/web/select-account.svg
packages/adena-extension/src/components/molecules/select-seed-phrase-box/index.tsx
packages/adena-extension/src/components/molecules/select-seed-phrase-box/select-seed-phrase-box-item.spec.tsx
packages/adena-extension/src/components/molecules/select-seed-phrase-box/select-seed-phrase-box-item.styles.tsx
packages/adena-extension/src/components/molecules/select-seed-phrase-box/select-seed-phrase-box-item.tsx
packages/adena-extension/src/components/molecules/select-seed-phrase-box/select-seed-phrase-box.spec.tsx
packages/adena-extension/src/components/molecules/select-seed-phrase-box/select-seed-phrase-box.styles.tsx
packages/adena-extension/src/components/molecules/select-seed-phrase-box/select-seed-phrase-box.tsx
packages/adena-extension/src/components/molecules/select-seed-phrase-box/select-seed-phrase-box.types.ts
packages/adena-extension/src/hooks/web/use-account-add-screen.ts
packages/adena-extension/src/hooks/web/use-account-import-screen.ts
packages/adena-extension/src/pages/web/account-add-screen/create-account-step.tsx
packages/adena-extension/src/pages/web/account-add-screen/index.tsx
packages/adena-extension/src/pages/web/account-add-screen/select-seed-phrase-step.tsx
packages/adena-extension/src/pages/web/account-import-screen/index.tsx
packages/adena-extension/src/pages/web/account-import-screen/select-account-step.tsx
packages/adena-module/src/wallet/wallet.ts

- feature
- Added a new "Create New Wallet" flow that supports the entry of multiple mnemonic phrases.
- Updated UI components to handle multiple mnemonics during add a wallet account.

feat: add an Create-New-Wallet flow to support multiple mnemonics

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.12.0.

chore: bump package version to 1.12.0

---

packages/adena-extension/src/pages/popup/wallet/broadcast-transaction-screen/upload.tsx

- bug
- On the Broadcast transaction page in Airgap account, change the URL external link for the `How Does it work` button.

fix: link to the airgap help page

---

packages/adena-extension/src/hooks/web/use-account-import-screen.ts

- feat
- Add validation logic when adding seed phrases.
- If you enter an invalid seed phrase, the error message ‘Invalid seed phrase’ is displayed.

feat: add validation logic when adding seed phrases

---

packages/adena-extension/src/pages/web/account-import-screen/index.tsx

- bug
Modify the dependency of useMemo to update UI variables.
- Modify the `extended` variable to update whenever the `step` changes.

fix: modify the dependency of useMemo to update UI variables

---

packages/adena-extension/src/hooks/web/use-account-import-screen.ts
packages/adena-extension/src/pages/web/account-import-screen/select-account-step.tsx

- bug
- On the Select account screen, update the loaded account data.

fix: update selectable accounts

---

packages/adena-extension/package.json
packages/adena-extension/src/inject.ts
packages/adena-extension/src/inject/executor/executor.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/message.ts
packages/adena-extension/src/inject/message/methods/common.ts
packages/adena-extension/src/inject/message/methods/network.ts
packages/adena-extension/src/inject/message/methods/transaction.ts
packages/adena-extension/src/inject/message/methods/wallet.ts
packages/adena-extension/src/inject/types/common.ts
packages/adena-extension/src/inject/types/events.ts
packages/adena-extension/src/inject/types/general.ts
packages/adena-extension/src/inject/types/index.ts
packages/adena-extension/src/inject/types/network.ts
packages/adena-extension/src/inject/types/transactions.ts
packages/adena-extension/src/pages/popup/wallet/approve-adding-network/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-changing-network/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-establish/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-login/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign-ledger-loading/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign-transaction-ledger-loading/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign-transaction/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-ledger-loading/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx
yarn.lock

- feat
- Add the adena-wallet-sdk dependency.
- Defines the response type of the Adena wallet's injection function. 
- Apply the adena-wallet-sdk response type.

feat: apply the adena-wallet-sdk response type

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.13.0.

chore: bump package version to 1.13.0

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.13.1.

chore: bump package version to 1.13.1

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.13.2.

chore: bump package version to 1.13.2

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.13.3.

chore: bump package version to 1.13.3

---

packages/adena-extension/src/resources/faucet/faucet-api.json

- chore
- Change the faucet API url.

chore: change the faucet API url

---

packages/adena-extension/src/common/utils/browser-utils.ts
packages/adena-extension/src/pages/popup/certify/launch-adena/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-login/index.tsx

- feature
- Add missing Forgot password logic to injection login page

Feat [ADN-629] Add forgot password button in injection UI

---

README.md

- chore
- Add the project environment to Readme.

chore: update project environments in readme

---

packages/adena-extension/src/hooks/use-clear.tsx
packages/adena-extension/src/hooks/use-extension-window-manager.tsx

- bug
- Fixed multiple registration pages appearing on wallet initialization.

fix: [ADN-572] Prevent duplicate pages on wallet-reset

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.14.0.

chore: bump package version to 1.14.0

---

packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction/index.tsx
packages/adena-extension/src/hooks/wallet/use-network-fee.ts
packages/adena-extension/src/inject/types/transactions.ts
packages/adena-extension/src/pages/popup/wallet/approve-sign-transaction/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/services/transaction/transaction.ts

- feature
- Apply a dynamic fee to the Injection popup.

feat: apply dynamic gas fee in injection popup

---

packages/adena-extension/public/manifest.json

- chore
- Add the `default-src` policy.
- Restrict unused `data:` sources.
- Restrict `frame-src`.
- Allow only local addresses from 127.0.0.1:26657.

chore: update content security policy

---

packages/adena-extension/src/common/constants/command-key.constant.ts
packages/adena-extension/src/components/pages/router/side-menu-layout/side-menu-container.tsx
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/commands/popup.ts
packages/adena-extension/src/router/web/index.tsx
packages/adena-extension/src/styles/global-style.ts

- feature
- Restricts access to the wallet settings page when the wallet is locked. 
- When you lock your wallet, exit any open extension pages.

feat: restricts access to the wallet settings page

---

packages/adena-extension/public/manifest.json
packages/adena-extension/src/background.ts
packages/adena-extension/src/common/constants/alarm-key.constant.ts
packages/adena-extension/src/common/provider/memory/memory-provider.ts
packages/adena-extension/src/common/utils/crypto-utils.ts
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/repositories/wallet/wallet.ts
packages/adena-module/src/crypto/libsodium.ts

- feature
- Implement the wallet auto-lock feature.
- The default value is 5 minutes.
- Generates an alarm from the alarm API when no extension tabs are active.
- Removes the encrypted password and key if the lockout time has passed.

feat: implements wallet auto-lock feature

---

packages/adena-extension/public/manifest.json
packages/adena-extension/src/background.ts
packages/adena-extension/src/components/atoms/button/index.tsx
packages/adena-extension/src/components/atoms/default-input/index.tsx
packages/adena-extension/src/components/atoms/highlight-number/highlight-number.styles.ts
packages/adena-extension/src/components/atoms/lottie/index.tsx
packages/adena-extension/src/components/atoms/status-dot/index.tsx
packages/adena-extension/src/components/atoms/text/index.tsx
packages/adena-extension/src/components/atoms/web-button/index.tsx
packages/adena-extension/src/components/atoms/web-copy-button/index.tsx
packages/adena-extension/src/components/atoms/web-main/index.tsx
packages/adena-extension/src/components/atoms/web-seed-input-item/index.tsx
packages/adena-extension/src/components/molecules/token-balance/token-balance.styles.ts

- bug
- Remove console errors.
- Clean up Auto Lock's alarm initialization logic.

fix: fix a minor issues

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.14.1.

chore: bump package version to 1.14.1

---

packages/adena-extension/src/background.ts
packages/adena-extension/src/common/constants/command-key.constant.ts
packages/adena-extension/src/common/constants/metatag.constant.ts
packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/common/validation/validation-message.ts
packages/adena-extension/src/content.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-info.ts
packages/adena-extension/src/hooks/wallet/use-network-fee.ts
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/methods/gno-connect.ts
packages/adena-extension/src/inject/message/methods/network.ts
packages/adena-extension/src/inject/message/methods/transaction.ts
packages/adena-extension/src/inject/message/methods/wallet.ts
packages/adena-extension/src/inject/types/transactions.ts
packages/adena-extension/src/pages/popup/wallet/approve-changing-network/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx

- feature
Based on https://github.com/gnolang/gno/issues/3610, 
it parses the website's `gnoconnect` meta tag and URL to create a transaction.
- Parses the meta tags `gnoconnect:rpc`, `gnoconnect:chainid`.
- Create a transaction by parsing a URL of the form `{packagePath}$help&func={function}&send={sendAmount}&args...`.
[Example]
https://github.com/user-attachments/assets/6c2bd390-5d18-4bdc-8649-acf79e90e78c

feat: parse gno metadata and generate transaction

---

packages/adena-extension/src/common/constants/gas.constant.ts
packages/adena-extension/src/common/provider/adena/adena-provider.tsx
packages/adena-extension/src/common/provider/gno/gno-provider.ts
packages/adena-extension/src/common/utils/fetch-utils.ts
packages/adena-extension/src/components/atoms/skeleton-box/index.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.spec.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction/index.tsx
packages/adena-extension/src/components/molecules/bottom-fixed-loading-button-group/index.tsx
packages/adena-extension/src/components/molecules/network-fee-custom-input/network-fee-custom-input.tsx
packages/adena-extension/src/components/molecules/network-fee/network-fee.styles.ts
packages/adena-extension/src/components/molecules/network-fee/network-fee.tsx
packages/adena-extension/src/components/pages/transfer-summary/transfer-summary/transfer-summary.styles.ts
packages/adena-extension/src/components/pages/transfer-summary/transfer-summary/transfer-summary.tsx
packages/adena-extension/src/hooks/use-balance-input.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-info.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-price-tiers.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-gas-price.ts
packages/adena-extension/src/hooks/wallet/use-network-fee.ts
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-input/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-summary/index.tsx
packages/adena-extension/src/repositories/transaction/transaction-gas.ts
packages/adena-extension/src/states/transfer.ts
packages/adena-extension/src/types/router.ts

- feature
- Handle a dynamic gas prices.
- Dynamically fetch the gas price value from indexer instead of the default gas price value.
- This isn't the exact gas price on-chain, but it's a good estimate of the gas price at which the transaction succeeds.

fix: handle dynamic gas prices

---

packages/adena-extension/src/components/atoms/default-input/index.tsx

- style
- Change password input text spacing in login page.

styles: login password input styles

---

packages/adena-extension/src/background.ts
packages/adena-extension/src/common/storage/chrome-local-storage.ts
packages/adena-extension/src/common/utils/crypto-utils.ts
packages/adena-extension/src/hooks/certify/use-change-password.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/methods/common.ts
packages/adena-extension/src/inject/message/methods/core.ts
packages/adena-extension/src/inject/message/methods/network.ts
packages/adena-extension/src/inject/message/methods/transaction.ts
packages/adena-extension/src/inject/message/methods/wallet.ts
packages/adena-extension/src/migrates/storage-migrator.ts
packages/adena-extension/src/pages/popup/certify/login/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-login/index.tsx
packages/adena-extension/src/repositories/wallet/wallet.ts
packages/adena-extension/src/services/wallet/wallet.ts

- fix
- Handle a encrypted password.
- Migrate encrypted wallet data.

fix: handle a encrypted password

---

packages/adena-extension/src/common/constants/tx.constant.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-info.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-price-tiers.ts

- feature
- Set the default gas wanted to the maximum value.

fix: set default gas wanted

---

packages/adena-extension/src/migrates/migrations/v009/storage-migration-v009.ts

- bug
- Under Data migration, add Migrate address book data.

fix: migrate address book

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.15.0.

chore: bump package version v1.15.0

---

packages/adena-extension/src/background.ts
packages/adena-extension/src/common/constants/metatag.constant.ts
packages/adena-extension/src/common/utils/crypto-utils.ts
packages/adena-extension/src/content.ts
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/command-message.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/methods/gno-connect.ts
packages/adena-extension/src/repositories/wallet/wallet.ts
yarn.lock

- feature
- Adena determines that if the `gnoconnect` tag is present, it is gno web.
- Add an interceptor for the anchor tag when it is gno web.
- Detects and intercept clicks on gno web transaction links.
- When you access a URL directly, you are directed to the page and a transaction popup is generated.
https://github.com/user-attachments/assets/3e33507b-34e1-48d9-8114-5d11cfdfb8be
https://github.com/user-attachments/assets/885d1cf9-4bc9-4b0a-88db-b41d99ed1614

feat: add a tx link interceptor

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.16.0.

chore: bump package version v1.16.0

---

packages/adena-extension/src/common/constants/tx-error.constant.ts
packages/adena-extension/src/common/provider/gno/gno-provider.ts
packages/adena-extension/src/common/provider/gno/utils.ts
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.spec.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction/index.tsx
packages/adena-extension/src/components/molecules/network-fee/network-fee.tsx
packages/adena-extension/src/components/pages/network-fee-setting/network-fee-setting/network-fee-setting.tsx
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-info.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-price-tiers.ts
packages/adena-extension/src/hooks/wallet/use-network-fee.ts
packages/adena-extension/src/types/gas.ts

- feature
- Handle on transaction Simulate errors .
- If the simulation fails, it shows a failure error message.
- If the simulation fails, disable the Approve button.

feat: handle on transaction simulate errors

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.16.1.

chore: bump package version to v1.16.1

---

packages/adena-extension/src/common/mapper/transaction-mapper.ts
packages/adena-extension/src/components/molecules/approve-transaction-loading/approve-transaction-loading.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction-message-box/approve-transaction-message-box.tsx
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction/index.tsx
packages/adena-extension/src/components/molecules/argument-edit-box/argument-edit-box.styles.ts
packages/adena-extension/src/components/molecules/argument-edit-box/argument-edit-box.tsx
packages/adena-extension/src/components/molecules/network-fee/network-fee.tsx
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/methods/gno-connect.ts
packages/adena-extension/src/inject/types/transactions.ts
packages/adena-extension/src/pages/popup/wallet/approve-sign-transaction/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx

- feature
- Fixes a minor UI issue with the Approve Transaction popup.

feat: adjust approve transaction popup ui

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to 1.16.2.

chore: bump package version to v1.16.2

---

packages/adena-extension/src/common/constants/alarm-key.constant.ts
packages/adena-extension/src/common/validation/validation-transaction.ts
packages/adena-extension/src/inject/message/commands/encrypt.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/methods/core.ts
packages/adena-extension/src/inject/message/methods/transaction.ts
packages/adena-extension/src/pages/popup/wallet/approve-sign-transaction/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx

- bug
- Fixes an error where commands could not be executed because the Adena instance was lost after auto-lock.
- Fixes alarm cycle to prevent extensions from being disabled.
- Add exception handling when loading In-Memory.

fix: fix for instance miss after auto-lock

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.16.4.

chore: bump package version to v1.16.4

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.16.5.

chore: bump package version to v1.16.5

---

packages/adena-extension/src/migrates/migrations/v010/storage-migration-v010.spec.ts
packages/adena-extension/src/migrates/migrations/v010/storage-migration-v010.ts
packages/adena-extension/src/migrates/migrations/v010/storage-model-v010.ts
packages/adena-extension/src/resources/chains/chains.json
packages/adena-extension/src/resources/faucet/faucet-api.json

- feature
- Add the testnet6 information to the default network information.
- Migration code is added to the installed extensions to support testnet6.

feat: support for test6 network

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.16.6.

chore: bump package version to v1.16.6

---

packages/adena-extension/public/manifest.json
packages/adena-extension/src/background.ts
packages/adena-extension/src/common/event-store/event-store.ts
packages/adena-extension/src/common/event-store/index.ts
packages/adena-extension/src/common/event-store/transaction-event-store.ts
packages/adena-extension/src/common/event-store/types.ts
packages/adena-extension/src/common/event-store/utility.ts
packages/adena-extension/src/inject.ts
packages/adena-extension/src/inject/executor/executor.ts
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/message.ts
packages/adena-extension/src/inject/message/methods/notification.ts
packages/adena-extension/src/inject/message/methods/transaction-event.ts
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/pages/popup/wallet/nft-transfer-summary/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-ledger-loading/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-summary/index.tsx

This PR implements Chrome web push notification for transaction broadcasting in the Adena Wallet extension. When a transaction is broadcasted, users will receive notifications about the transaction status (pending, success, or failure) and can click on the notification to view transaction details in the block explorer.
- Added "notifications" permission to Chrome extension manifest
- Created a transaction event store to track and update transaction statuses
- Implemented notification system for transactions with three states: pending, success, and failed
- Added click handling for notifications to open transaction details in block explorer
- Modified transaction handling to include notification option
- The transaction event store (`TransactionEventStore`) manages the lifecycle of …

feat: implement a chrome web push notification

---

packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx
packages/adena-extension/src/components/molecules/approve-transaction/index.tsx

- bug
- Handle approve button activation.
- Handle a simulate data.

fix: adjust handle transaction data in siumlate 

---

packages/adena-extension/src/hooks/web/wallet-export/use-wallet-export-screen.ts

- bug
- Remove questionnaire step in wallet export.

fix: remove questionnaire step in wallet export

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.17.0.

chore: bump package version to v1.17.0

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.17.2.

chore: bump package version to v1.17.2

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.17.3.

chore: bump package version to v1.17.3

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.17.4.

chore: bump package version to v1.17.4

---

packages/adena-extension/src/migrates/migrations/v011/storage-migration-v011.spec.ts
packages/adena-extension/src/migrates/migrations/v011/storage-migration-v011.ts
packages/adena-extension/src/migrates/migrations/v011/storage-model-v011.ts
packages/adena-extension/src/migrates/storage-migrator.spec.ts
packages/adena-extension/src/migrates/storage-migrator.ts
packages/adena-extension/src/resources/chains/chains.json
packages/adena-extension/src/resources/faucet/faucet-api.json

- chore
- Support for testnet7 network.

chore: support testnet7

---

package.json
packages/adena-extension/package.json
packages/adena-extension/public/manifest.json
packages/adena-module/package.json

- chore
- Update adena wallet package version to v1.17.5.

chore: bump package version to v1.17.5

---

packages/adena-module/src/libs/gno-js-client/proto/gno/vm.ts

- bug
- Fix a vm proto messages.
- After updating `gno-js-client`, change it to use the proto model of `gno-js-client`.

fix: vm proto messages

---

packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx

- feature
- Reorganized the display order of transaction arguments in the ApproveTransactionMessage component to improve the user experience.
- argument to raw.

feat: Reorder transaction arguments in ApproveTransactionMessage

---

packages/adena-extension/src/components/molecules/approve-transaction/index.tsx
packages/adena-extension/src/components/molecules/storage-deposit/storage-deposit.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx

- bug
- Fix a storage max deposit error messages.

fix: storage deposit error message
