packages/adena-extension/src/inject/message/methods/transaction.ts

When trying to sign a message with type `/vm.m_addpkg` it throws the error `UNSUPPORTED_TYPE` because it's missing a `break` in the validation.

fix: addpkg message validation

---

packages/adena-extension/src/common/storage/chrome-local-storage.ts
packages/adena-extension/src/common/storage/storage-manager.ts
packages/adena-extension/src/common/storage/storage.ts
packages/adena-extension/src/migrates/migrations/v001/storage-model-v001.ts
packages/adena-extension/src/migrates/migrations/v002/storage-migration-v002.spec.ts
packages/adena-extension/src/migrates/migrations/v002/storage-migration-v002.ts
packages/adena-extension/src/migrates/migrations/v002/storage-model-v002.ts
packages/adena-extension/src/migrates/migrator.ts
packages/adena-extension/src/migrates/storage-migrator.spec.ts
packages/adena-extension/src/migrates/storage-migrator.ts
packages/adena-extension/src/repositories/wallet/wallet.ts
packages/adena-extension/src/services/wallet/wallet.ts
packages/adena-extension/tsconfig.json
packages/adena-extension/webpack.config.js

Add version to data stored per storage. (Default: 1)
Adds the ability to proceed with migration by version (version 1 → version 2 → version 3, etc.)
Create backup data for data restoration in case of migration failure.

feat: [ADN-203] Add data migration

---

packages/adena-extension/src/common/utils/encoding-util.ts
packages/adena-extension/src/containers/make-transaction-container/make-transaction-container.tsx
packages/adena-extension/src/containers/make-transaction-ledger-loading-container/make-transaction-ledger-loading-container.tsx
packages/adena-extension/src/inject.ts
packages/adena-extension/src/inject/executor/executor.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/message.ts
packages/adena-extension/src/inject/message/methods/transaction.ts
packages/adena-extension/src/router/custom-router.tsx
packages/adena-extension/src/router/path.ts

Based on #282, We need to review the purpose of this PR. 
`adena.MakeTx` method returns encoded transaction data.

feat: Add `adena.MakeTx` method

---

packages/adena-extension/src/common/utils/client-utils.ts
packages/adena-extension/src/common/validation/validation-message.ts
packages/adena-extension/src/inject/executor/executor.ts
packages/adena-extension/src/inject/message/methods/transaction.ts
packages/adena-extension/src/pages/wallet/transaction-detail/use-status.ts
packages/adena-extension/src/services/transaction/message/vm/vm.ts
packages/adena-module/src/transaction/message-info/message-info-vm.ts
packages/adena-module/src/transaction/transaction-builder.ts
packages/adena-module/src/transaction/transaction.ts

Add handlers for the new message type: https://github.com/gnolang/gno/pull/1001

feat: add `/vm.m_run` message handler

---

packages/adena-module/src/utils/messages.ts
packages/adena-module/src/wallet/keyring/address-keyring.spec.ts

- bug
- Fixes an error where signature data is not encoded when reading string data from a transaction file

fix: Fix signature encoding when loading transaction file

---

packages/adena-extension/package.json
packages/adena-module/package.json
yarn.lock

- chore
- Updated the version of the @gnolang/gno-js-client dependency

chore(deps): bump @gnolang/gno-js-client from 1.2.0 to 1.2.1

---

packages/adena-extension/public/manifest.json
packages/adena-extension/src/App/app-provider.tsx
packages/adena-extension/src/App/popup.tsx
packages/adena-extension/src/background.ts
packages/adena-extension/src/common/error-boundary/app-provider-error-boundary.tsx
packages/adena-extension/src/common/error-boundary/fallback/app-reload-fallback.tsx
packages/adena-extension/src/common/error-boundary/fallback/index.ts
packages/adena-extension/src/common/error-boundary/index.ts
packages/adena-extension/src/common/errors/common/common-error.ts
packages/adena-extension/src/common/storage/chrome-local-storage.ts
packages/adena-extension/src/common/storage/chrome-session-storage.ts
packages/adena-extension/src/hooks/use-clear.tsx
packages/adena-extension/src/hooks/use-init-wallet.tsx
packages/adena-extension/src/hooks/use-wallet.ts
packages/adena-extension/src/router/popup/index.tsx
packages/adena-extension/src/services/wallet/wallet.ts
packages/adena-extension/webpack.config.js

- bug
- Resolve an error that the chrome API is not found when the extension is run on the web in certain browsers.
- Throws an error if no objects from the chrome API are found, and reloads the page.
- Related issue: #437

fix: Unable to add new account to existing wallet

---

packages/adena-extension/src/components/molecules/web-seed-input/index.tsx

- bug
- Fix disabled button bug when pasting 24-word mnemonic into the 12-word field

fix: Fix mnemonic handling on the Import Wallet screen

---

packages/adena-extension/src/inject/message/methods/wallet.ts

- feature
- `adena.AddEstablish()` function returns a success response if the website is already registered.

feat: Allow AddEstablish to connect to an already connected app

---

packages/adena-extension/src/resources/chains/chains.json

- chore
- Change network information to be editable except for official networks.

chore: Only lock testnet3 and portal-loop from the network list

---

packages/adena-extension/src/App/use-app.ts
packages/adena-extension/src/components/pages/router/side-menu-layout/side-menu-container.tsx
packages/adena-extension/src/components/pages/router/side-menu/side-menu.tsx
packages/adena-extension/src/hooks/use-balance-input.ts
packages/adena-extension/src/hooks/use-token-balance.ts
packages/adena-extension/src/hooks/use-token-metainfo.tsx
packages/adena-extension/src/hooks/use-wallet-accounts.tsx
packages/adena-extension/src/pages/popup/wallet/manage-token-added/index.tsx
packages/adena-extension/src/pages/popup/wallet/manage-token/index.tsx
packages/adena-extension/src/pages/popup/wallet/search/index.tsx
packages/adena-extension/src/pages/popup/wallet/token-details/index.tsx
packages/adena-extension/src/pages/popup/wallet/transaction-detail/index.tsx
packages/adena-extension/src/pages/popup/wallet/wallet-main/index.tsx
packages/adena-extension/src/router/popup/loading-main.tsx
packages/adena-extension/src/services/wallet/wallet-balance.ts

- feature
- The wallet periodically patches the account's balance.
- Change to use React Query.

feat: Apply data auto refresh

---

packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/methods/common.ts

- bug
- Changed to remove popups except for the injection popup when running an injection with a tab open in a popup window.
- This resolves an error that occurs when running an injection popup, if one exists.

fix: Fix injection and pop window collision

---

packages/adena-extension/src/App/use-app.ts
packages/adena-extension/src/components/molecules/error-container/index.tsx
packages/adena-extension/src/hooks/use-add-account.tsx
packages/adena-extension/src/hooks/use-clear.tsx
packages/adena-extension/src/hooks/use-network.ts
packages/adena-extension/src/hooks/use-remove-account.tsx
packages/adena-extension/src/hooks/web/use-account-add-screen.ts
packages/adena-extension/src/router/popup/header/index.tsx
packages/adena-extension/src/router/popup/index.tsx
packages/adena-extension/src/router/popup/loading-main.tsx
packages/adena-extension/src/router/popup/navigation/index.tsx
packages/adena-extension/src/states/common.ts

- bug
- Fixes a bug in the wallet that causes persistent loading after a network change.
- Change network state variables to be managed by React Query.
- Reference Issue: https://github.com/onbloc/adena-wallet/issues/480

fix: Fix Infinity loading

---

packages/adena-extension/package.json
packages/adena-module/package.json
packages/adena-module/src/wallet/keyring/hd-wallet-keyring.ts
packages/adena-module/src/wallet/keyring/keyring-util.ts
packages/adena-module/src/wallet/keyring/ledger-keyring.ts
packages/adena-module/src/wallet/keyring/private-key-keyring.ts
packages/adena-module/src/wallet/keyring/web3-auth-keyring.ts
yarn.lock

- feature
- Due to changes in the signing process, we use a separate `tm2-js-client` for each network.
- The `test3` network uses an `tm2-js-client@1.1.7`.

feat: Use a separate tm2-js-client per network

---

packages/adena-extension/package.json
packages/adena-extension/src/common/validation/validation-message.ts
packages/adena-extension/src/hooks/wallet/broadcast-transaction/use-broadcast-transaction-screen.ts
packages/adena-module/package.json
packages/adena-module/src/utils/messages-legacy.ts
packages/adena-module/src/wallet/keyring/hd-wallet-keyring.ts
packages/adena-module/src/wallet/keyring/keyring-util.ts
packages/adena-module/src/wallet/keyring/ledger-keyring.ts
packages/adena-module/src/wallet/keyring/private-key-keyring.ts
packages/adena-module/src/wallet/keyring/web3-auth-keyring.ts
packages/adena-module/src/wallet/wallet-sign.spec.ts
yarn.lock

- feature
Update to changes in https://github.com/gnolang/gno-js-client/pull/132.
- Change the fields in the transaction message package to lowercase.
- Add code to support the testnet3 network.
Additionally, legacy dependencies will be removed after the testnet4 launch.

feat: change to lowercase to field names for Gno VM `MsgCall` and support legacy field

---

packages/adena-extension/src/components/molecules/web-help-overlay/web-help-overlay.stories.tsx
packages/adena-extension/src/components/molecules/web-help-overlay/web-help-overlay.tsx
packages/adena-extension/src/components/molecules/web-help-tooltip/web-help-tooltip.styles.ts
packages/adena-extension/src/components/molecules/web-help-tooltip/web-help-tooltip.tsx
packages/adena-extension/src/components/pages/web/wallet-creation-help-overlay/wallet-creation-help-overlay.tsx

- fix
Resolve #527 issues. 
Expose the tooltip at the top if its position exceeds the screen size.
[Default]
[Responseive]

fix: responsive positioning of help tooltips

---

packages/adena-extension/src/components/molecules/select-account-box/select-account-box-item.tsx
packages/adena-extension/src/hooks/web/use-account-add-screen.ts
packages/adena-extension/src/hooks/web/use-account-import-screen.ts
packages/adena-extension/src/pages/web/account-add-screen/index.tsx

- bug
- Shows the account address without omitting any characters.
- When adding an account to an existing mnemonic, skip the prompts.
- Fix the UI to be centred during the account selection process.
- Fixes a bug that prevented updating accounts by mnemonic when selecting an account.

fix: fix bugs during multiple mnemonics processing

---

packages/adena-extension/src/pages/web/account-import-screen/index.tsx

- styles
- On the screen for adding an account with Mnemonic Wallet, align the component to the centre.

fix: fix a ui align center in select account

---

packages/adena-extension/src/common/constants/resource.constant.ts

- chore
- Change the link URL to the Gno CLI documentation. 
(https://docs.gno.land/gno-tooling/cli/gnokey/working-with-key-pairs)

chore: update gno docs link url

---

packages/adena-extension/src/components/atoms/copy-icon-button/index.tsx
packages/adena-extension/src/components/atoms/highlight-number/index.tsx
packages/adena-extension/src/components/molecules/token-balance/token-balance.styles.ts
packages/adena-extension/src/components/pages/account-details/account-details/account-details.spec.tsx
packages/adena-extension/src/components/pages/account-details/account-details/index.tsx
packages/adena-extension/src/components/pages/router/side-menu-account-item/side-menu-account-item.spec.tsx
packages/adena-extension/src/components/pages/router/side-menu-account-item/side-menu-account-item.tsx
packages/adena-extension/src/components/pages/router/side-menu-account-list/side-menu-account-list.spec.tsx
packages/adena-extension/src/components/pages/router/side-menu-account-list/side-menu-account-list.tsx
packages/adena-extension/src/components/pages/router/side-menu-layout/side-menu-container.tsx
packages/adena-extension/src/components/pages/router/side-menu/side-menu.spec.tsx
packages/adena-extension/src/components/pages/router/side-menu/side-menu.tsx
packages/adena-extension/src/pages/popup/wallet/account-details/index.tsx
packages/adena-extension/src/types/side-menu.ts

- feature
- Resize the decimal text in the side menu account balance for readability.
- Adjust the spacing between the balance and the symbol in components that show common balances.
- Change the event that exits the dropdown in the side menu to fire when the mouse is clicked.
- Add a button to navigate to the Reveal Seed Phrase page from the account details page.

feat: improve the account with side menu UI

---

packages/adena-extension/src/App/use-app.ts
packages/adena-extension/src/hooks/use-token-metainfo.tsx

- feature
- Retrieves a list of packages for which the account's Transfer event was fired.
- When initialized, the wallet registers any unsaved GRC20 packages.
- When initialized, the wallet registers GRC721 packages that are not stored.

feat: enhance tokens management

---

packages/adena-extension/package.json
packages/adena-extension/src/inject.ts
packages/adena-extension/src/inject/executor/executor.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/inject/message/methods/wallet.ts
packages/adena-extension/src/inject/types/general.ts
packages/adena-extension/src/inject/types/network.ts
yarn.lock

- feature
Add a method to inject that retrieves the current network information.
Users can retrieve network information by executing `adena.GetNetwork()`.
Example response.
```
{
“status": “success”,
“data": {
“chainId": “test4”,
“networkName": “Testnet 4”,
“addressPrefix": “g”,
“rpcUrl": “https://rpc.test4.gno.land:443”,
“indexerUrl": “https://test4.indexer.onbloc.xyz”
},
“code": 0,
“message": “Get Network Information.”,
“type": “GET_NETWORK”
}
```

feat: add a injection method to get network information

---

packages/adena-extension/src/components/molecules/manage-token-list/manage-token-list-item.tsx
packages/adena-extension/src/components/molecules/token-balance/token-balance.styles.ts
packages/adena-extension/src/components/molecules/transaction-history/transaction-history-list-item/transaction-history-list-item.tsx
packages/adena-extension/src/components/molecules/transaction-history/transaction-history-list/transaction-history-list.tsx
packages/adena-extension/src/components/pages/nft-collection/nft-collection-assets/nft-collection-assets.styles.ts
packages/adena-extension/src/components/pages/nft/nft-collection-card/nft-collection-card.tsx
packages/adena-extension/src/components/pages/nft/nft-collections/nft-collections.styles.ts
packages/adena-extension/src/hooks/nft/use-get-grc721-balance.ts
packages/adena-extension/src/hooks/nft/use-get-grc721-tokens.ts
packages/adena-extension/src/hooks/use-make-transactions-with-time.ts
packages/adena-extension/src/hooks/use-token-metainfo.tsx
packages/adena-extension/src/hooks/wallet/token-details/use-token-transactions-page.ts
packages/adena-extension/src/hooks/wallet/token-details/use-token-transactions.ts
packages/adena-extension/src/hooks/wallet/transaction-history/use-transaction-history-page.ts
packages/adena-extension/src/hooks/wallet/transaction-history/use-transaction-history.ts
packages/adena-extension/src/pages/popup/wallet/history/index.tsx
packages/adena-extension/src/pages/popup/wallet/token-details/index.tsx
packages/adena-extension/src/repositories/transaction/mapper/transaction-history-query.mapper.ts

- bug
- On the transaction list page, change the token meta information to be applied correctly.
- Modify the style of the component that shows the amount of tokens.
- Fix UI issues on the NFT page.

fix: fix UI issues

---

packages/adena-extension/src/repositories/transaction/transaction-history.queries.ts

- bug
Fixes an issue where failed transactions are not shown in the Adena transaction history.
- Remove the `success` filter option from indexer queries that look up a list of transactions.
Related issues: https://github.com/onbloc/adena-wallet/issues/626

fix: change query filter options for retrieving failed transactions

---

packages/adena-extension/src/hooks/use-make-transactions-with-time.ts
packages/adena-extension/src/hooks/use-token-metainfo.tsx
packages/adena-extension/src/hooks/wallet/token-details/use-token-transactions-page.ts
packages/adena-extension/src/hooks/wallet/transaction-history/use-transaction-history-page.ts
packages/adena-extension/src/hooks/wallet/transaction-history/use-transaction-history.ts

- bug
Modify the token meta information on the token history page so that it is properly applied.
- Fix logic for mapping token metadata

fix: apply token metadata to transaction history

---

packages/adena-extension/src/components/molecules/manage-token-list/manage-token-list-item.tsx
packages/adena-extension/src/components/molecules/nft-card-image/nft-card-image.tsx
packages/adena-extension/src/components/molecules/transaction-history/transaction-history-list-item/transaction-history-list-item.tsx
packages/adena-extension/src/pages/popup/wallet/manage-token/index.tsx
packages/adena-extension/src/pages/popup/wallet/transaction-detail/index.tsx

- bug
- Fixes broken image regions when image data in GRC721 is not an image.
- Add exception handling in the form of showing the underlying data if an error occurs while displaying the image.

fix: handle invalid image paths

---

packages/adena-extension/src/App/use-app.ts
packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/hooks/use-token-balance.ts
packages/adena-extension/src/hooks/use-token-metainfo.tsx
packages/adena-extension/src/pages/popup/certify/change-network/index.tsx
packages/adena-extension/src/pages/popup/wallet/manage-token-added/index.tsx
packages/adena-extension/src/repositories/common/token.queries.ts
packages/adena-extension/src/repositories/common/token.ts
packages/adena-extension/src/services/wallet/wallet-balance.ts

- bug
Improve the process of retrieving token information for an account.
- Fixes the process of initializing token information when changing custom networks.
- Change the token information initialization function call to only be called from the parent hook or provider.

fix: improve the process of initializing token information

---

packages/adena-extension/src/components/molecules/nft-card-image/nft-card-image.tsx

- bug
Fixes an issue that prevented the GRC721 card image from displaying.

fix: display grc721 token uri

---

packages/adena-extension/src/components/pages/nft/nft-collections/nft-collections.tsx

- bug
Fixes an error where the Show option is not applied on the GRC721 collection manage page.
Filter the GRC721 collection with the display option.

fix: fix GRC721 display collection options

---

packages/adena-extension/src/App/use-app.ts
packages/adena-extension/src/common/provider/wallet/wallet-provider.tsx
packages/adena-extension/src/components/pages/wallet-main/token-list-item/token-list-item.spec.tsx
packages/adena-extension/src/components/pages/wallet-main/token-list-item/token-list-item.tsx
packages/adena-extension/src/components/pages/wallet-main/token-list/token-list.spec.tsx
packages/adena-extension/src/components/pages/wallet-main/token-list/token-list.tsx
packages/adena-extension/src/hooks/use-load-images.tsx
packages/adena-extension/src/pages/popup/wallet/wallet-main/index.tsx
packages/adena-extension/src/router/popup/loading-main.tsx
packages/adena-extension/src/states/common.ts

- feature
- The token image finishes loading and shows the main screen.
- Create a hook to check for token image loading.

feat: handle fetching token images

---

packages/adena-extension/src/pages/web/wallet-export-screen/result.tsx

- bug
- Fix the Export Private Key / Export Seed Phrase page exiting directly.
- Check that the exit button is initialized and enable the event.

fix: check the initialization status of the export page button

---

packages/adena-extension/src/router/popup/loading-main.tsx

- bug
- Prevent loading when the network fails.
- Change the exposure conditions for the loading screen.

fix: prevent loading when the network fails

---

packages/adena-extension/src/hooks/web/wallet-export/use-wallet-export-screen.ts

- bug
The desired account export did not occur when the action was run.

fix: [ADN-649] wrong seed when exporting via sidebar

---

packages/adena-extension/src/common/storage/chrome-local-storage.ts
packages/adena-extension/src/common/storage/chrome-session-storage.ts
packages/adena-extension/src/common/utils/amount-utils.ts
packages/adena-extension/src/common/utils/crypto-utils.ts
packages/adena-extension/src/hooks/use-faucet.ts
packages/adena-extension/src/migrates/storage-migrator.spec.ts
packages/adena-extension/src/migrates/storage-migrator.ts
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/pages/popup/wallet/nft-transfer-summary/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-summary/index.tsx
packages/adena-extension/src/services/resource/token.ts
packages/adena-extension/src/services/transaction/transaction-history.ts
packages/adena-extension/src/services/transaction/transaction.ts
packages/adena-extension/src/services/wallet/wallet-balance.ts
packages/adena-module/src/wallet/wallet.ts

- chore
- Add comments and cleanup codes.

chore: add comments and cleanup codes

---

packages/adena-extension/src/pages/popup/wallet/approve-login/index.tsx

- style
- Apply a responsive UI on the password entry page.

fix: apply responsive components to the `Enter Your Password` screen

---

packages/adena-extension/src/content.ts
packages/adena-extension/src/inject/executor/executor.ts

- fix
- Restrict event messages to be delivered only to the source on the current page.
The trusted domains that can then execute Adena commands are managed by an in-service feature in Adena.
- Check the event source address in the event message listener function.
- When sending an event message, specify the target origin.

fix: check the source when handling events

---

packages/adena-extension/src/components/atoms/web-copy-button/index.tsx
packages/adena-extension/src/pages/web/wallet-create-screen/get-mnemonic-step.tsx
packages/adena-extension/src/pages/web/wallet-export-screen/result.tsx

- feature
- Shows an error message when copying a user's mnemonic and private key to the clipboard.
- Sets the default timeout to clear the clipboard when copying the clipboard. (30 seconds)

feat: improve sensitive data exposure page

---

packages/adena-extension/src/background.ts
packages/adena-extension/src/common/constants/command-key.constant.ts
packages/adena-extension/src/common/provider/memory/memory-provider.ts
packages/adena-extension/src/common/utils/crypto-utils.ts
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/command-message.ts
packages/adena-extension/src/inject/message/commands/encrypt.ts
packages/adena-extension/src/inject/message/message-handler.ts
packages/adena-extension/src/repositories/wallet/wallet.ts

- feature
- Removed Static Key Usage:
- Eliminated the use of a hardcoded static encryption key (ENCRYPT_CIPHER_KEY), reducing the risk of key leakage or unauthorized access.
- Implemented AES-GCM:
- Transitioned from AES-CBC (CryptoJS) to AES-GCM using Web Crypto API, which provides built-in integrity verification through authentication tags.
- Introduced Initialization Vector (IV):
- Added a dynamically generated IV (crypto.getRandomValues) to ensure that identical inputs produce different encrypted outputs.
- In-Memory Key Management:
- Encryption keys are now stored only in memory using CryptoKey, ensuring they are not persisted in session or local storage.

feat: improve password encryption methods

---

packages/adena-extension/src/repositories/common/token.ts
packages/adena-extension/src/repositories/transaction/mapper/transaction-history-query.mapper.ts
packages/adena-extension/src/repositories/transaction/response/transaction-history-query-response.ts
packages/adena-extension/src/repositories/transaction/transaction-history.queries.ts

- fix
- When calling GraphQL, limit queries to schema and type names.
- Adena currently uses the GraphQL API from the [tx-indexer](https://github.com/gnolang/tx-indexer) open source project, and the introspection setting can be added to the project.

fix: add GraphQL introspection guard

---

packages/adena-extension/src/common/constants/gas.constant.ts
packages/adena-extension/src/common/provider/adena/adena-provider.tsx
packages/adena-extension/src/common/provider/gno/gno-provider.ts
packages/adena-extension/src/common/utils/fetch-utils.ts
packages/adena-extension/src/components/atoms/skeleton-box/index.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.spec.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction/index.tsx
packages/adena-extension/src/components/molecules/bottom-fixed-loading-button-group/index.tsx
packages/adena-extension/src/components/molecules/network-fee-custom-input/network-fee-custom-input.tsx
packages/adena-extension/src/components/molecules/network-fee/network-fee.styles.ts
packages/adena-extension/src/components/molecules/network-fee/network-fee.tsx
packages/adena-extension/src/components/pages/transfer-summary/transfer-summary/transfer-summary.styles.ts
packages/adena-extension/src/components/pages/transfer-summary/transfer-summary/transfer-summary.tsx
packages/adena-extension/src/hooks/use-balance-input.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-info.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-price-tiers.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-gas-price.ts
packages/adena-extension/src/hooks/wallet/use-network-fee.ts
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-input/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-summary/index.tsx
packages/adena-extension/src/repositories/transaction/transaction-gas.ts
packages/adena-extension/src/services/wallet/wallet.ts
packages/adena-extension/src/states/transfer.ts
packages/adena-extension/src/types/router.ts

- feature
- Handle a dynamic gas prices.
- Dynamically fetch the gas price value from indexer instead of the default gas price value.
- This isn't the exact gas price on-chain, but it's a good estimate of the gas price at which the transaction succeeds.

fix(cherry-pick): handle dynamic gas prices

---

packages/adena-extension/src/hooks/wallet/use-network-fee.ts

- bug
- Even if simulate fails, it shows the selected network fee.

fix: visible network fee when error

---

packages/adena-extension/src/common/utils/encoding-util.ts
packages/adena-extension/src/common/utils/rand-utils.ts
packages/adena-extension/src/components/molecules/web-private-key-box/index.tsx
packages/adena-extension/src/components/molecules/web-seed-box/index.tsx
packages/adena-extension/src/components/molecules/web-seed-box/web-seed-box.spec.tsx
packages/adena-extension/src/components/molecules/web-seed-box/web-seed-box.stories.tsx
packages/adena-extension/src/hooks/certify/use-create-password.ts
packages/adena-extension/src/hooks/web/common/use-create-password-screen.ts
packages/adena-extension/src/hooks/web/use-account-import-screen.ts
packages/adena-extension/src/hooks/web/use-wallet-create-screen.ts
packages/adena-extension/src/hooks/web/use-wallet-import-screen.ts
packages/adena-extension/src/hooks/web/wallet-export/use-wallet-export-screen.ts
packages/adena-extension/src/pages/popup/certify/change-password/index.tsx
packages/adena-extension/src/pages/popup/certify/create-password/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-login/index.tsx
packages/adena-extension/src/pages/web/create-password-screen/index.tsx
packages/adena-extension/src/pages/web/wallet-create-screen/get-mnemonic-step.tsx
packages/adena-extension/src/pages/web/wallet-export-screen/check-password.tsx
packages/adena-extension/src/pages/web/wallet-export-screen/result.tsx

- feature
- Clears personal data entered or provided to the user from memory.
- This can be done by removing it immediately or encoding it when storing it so that the actual value is not exposed in memory.

fix: clear sensitive data in memory

---

packages/adena-extension/src/components/molecules/approve-transaction-loading/approve-transaction-loading.spec.tsx
packages/adena-extension/src/components/molecules/approve-transaction-loading/approve-transaction-loading.stories.tsx
packages/adena-extension/src/components/molecules/approve-transaction-loading/approve-transaction-loading.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction-loading/index.tsx
packages/adena-extension/src/components/molecules/approve-transaction-message-box/approve-transaction-message-box.tsx
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.spec.tsx
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.spec.tsx
packages/adena-extension/src/components/molecules/approve-transaction/approve-transaction.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign-transaction/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-sign/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-transaction-main/index.tsx

- feature
Improve the UI of the transaction popup.
- By default, it allows the user to see the arguments of the transaction being executed.
- Improve the organization of the UI for usability.

feat: change the transaction approve popup transaction information UI

---

packages/adena-extension/src/components/molecules/argument-edit-box/argument-edit-box.styles.ts
packages/adena-extension/src/components/molecules/argument-edit-box/argument-edit-box.tsx

- bug
- Approve Transaction popup argument reverse order display error.
- Fixes an error where a leading special character is output after a special character in an argument that contains a special character.

fix: approve transaction popup argument reverse order display error

---

packages/adena-extension/src/common/utils/string-utils.ts
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.styles.ts
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx
packages/adena-extension/src/components/molecules/argument-edit-box/argument-edit-box.tsx

- bug
This pull request introduces a new utility function and updates several components to utilize this function for string manipulation. The most significant changes include the addition of the `reverseString` function and its integration into various components.
New utility function:
* [`packages/adena-extension/src/common/utils/string-utils.ts`](diffhunk://#diff-a8dfa8ca5f6992dc8f6e88c2376ea95960947833672343480780ec7feaac4a6bR49-R52): Added `reverseString` function to reverse a given string.
Component updates:
* [`packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx`](diffhunk://#diff-7af33d19ac48074e9c6260a7cd474e8595efa816ca5be2971192fb9a82b266c9L4-R4): Integrated `reverseString` function to reverse domain, namespace, and …

fix: realm path direction in approve transaction

---

packages/adena-extension/src/pages/popup/wallet/transfer-summary/index.tsx

- bug
Fix an error that caused transactions to fail with an incorrect gas wanted value when transferring GRC20 balances.
On the Token Transfer page, change to use the calculated gas wanted value.

fix: invalid gas wanted in grc20 transfer

---

packages/adena-extension/src/common/provider/gno/gno-provider.ts
packages/adena-extension/src/common/provider/gno/index.ts
packages/adena-extension/src/common/provider/gno/types.ts
packages/adena-extension/src/common/provider/gno/utils.ts
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/methods/gno-connect.ts
packages/adena-extension/src/services/wallet/wallet-account.ts

- feature
based on https://github.com/gnolang/gno/issues/4073,
Change the way messages are generated from Adena tx link.
Previously, Adena generated arguments based on the order of the parameters in tx link, 
but now Adena set the parameters based on the function information defined in the `vm/qdoc`.
- When generating a transaction message in tx link, it queries in `vm/qdoc` to set the order and number of arguments.
- When a parameter in tx link has a corresponding key value, it changes the value to a filled form.

feat: reorder arguments in tx link

---

packages/adena-extension/src/common/provider/gno/gno-provider.ts
packages/adena-extension/src/common/provider/gno/utils.ts
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/methods/gno-connect.ts

- bug
This pull request to the `packages/adena-extension` includes several changes to enhance the functionality and improve the robustness of the `GnoProvider` and related utilities. The most important changes include the addition of HTTPS protocol checking, refactoring of query path creation, and improvements to error handling.
Enhancements to protocol handling:
* [`packages/adena-extension/src/common/provider/gno/gno-provider.ts`](diffhunk://#diff-54090f0e7847331a6714c67a0c314e6d701b25327828565c0840d5700e8e8d8aL23-R29): Added `isHttpsAvailable` to check for HTTPS support and modified `makeRequestQueryPath` to `getRequestQueryPath` to use this check. [[1]](diffhunk://#diff-54090f0e7847331a6714c67a0c314e6d701b25327828565c0840d5700e8e8d8aL23-R29) …

fix: handle gnoconnect rpc protocol

---

packages/adena-extension/src/inject/message/command-handler.ts

- bug
This pull request includes an important change to the `CommandHandler` class in the `command-handler.ts` file to improve the handling of domain-specific connections.
Key change:
* [`packages/adena-extension/src/inject/message/command-handler.ts`](diffhunk://#diff-ecd5a5447eb29ea9646cd5d50b2fceb3533a8e5554d22b2b8bb4d04bde9138b6L106-R107): Modified the `addEstablish` method to include the domain extracted from the current window's URL, enhancing domain-specific connection handling.

fix: connect to unknown in add establish

---

packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx

- bug
This pull request includes minor changes to the `approve-transaction-message.tsx` file, primarily focusing on debugging and correcting a logical condition.
Code debugging:
* Added a `console.log` statement to output the `paths` variable for debugging purposes. (`packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx`)
Logical condition correction:
* Modified the condition to check the length of `paths` for determining `namespaceSubPath` to be more accurate. (`packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.tsx`)

fix: missing realm sub path

---

packages/adena-extension/src/components/atoms/web-seed-validate-input-item/index.tsx
packages/adena-extension/src/components/atoms/web-seed-validate-input-item/web-seed-input.stories.tsx
packages/adena-extension/src/hooks/web/common/use-create-password-screen.ts
packages/adena-extension/src/hooks/web/use-wallet-create-screen.ts
packages/adena-extension/src/pages/web/create-password-screen/index.tsx
packages/adena-extension/src/pages/web/wallet-create-screen/index.tsx
packages/adena-extension/src/pages/web/wallet-create-screen/validate-mnemonic-step.tsx

- feature
This PR adds a verification step to the wallet creation flow that requires users to confirm their seed phrase by entering specific words from it. This ensures users have properly recorded their seed phrase before proceeding to wallet creation.
- Added a new step `VALIDATE_MNEMONIC` to the wallet creation flow
- Created a new component `WebSeedValidateInputItem` for seed word input validation
- Implemented `ValidateMnemonicStep` component to handle the verification process
- Updated the wallet creation flow to include the verification step between showing the seed phrase and creating the wallet
1. After viewing their seed phrase, users are presented with a verification screen
2. The system randomly selects two words from the seed phrase
3. Users must correctly enter these words …

feat: add a seed verification process a few words

---

packages/adena-extension/src/common/constants/gas.constant.ts
packages/adena-extension/src/common/provider/gno/gno-provider.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-info.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-estimate-gas-price-tiers.ts
packages/adena-extension/src/hooks/wallet/transaction-gas/use-get-gas-price.ts
packages/adena-extension/src/hooks/wallet/use-network-fee.ts
packages/adena-extension/src/repositories/transaction/transaction-gas.ts
packages/adena-extension/src/repositories/transaction/types.ts
packages/adena-extension/src/services/transaction/transaction-gas.ts
packages/adena-extension/src/services/transaction/types.ts

- feature
This PR implements direct gas price querying from the chain instead of using the indexer. The changes include updating the gas price calculation logic and simplifying the related interfaces.
- Implement `getGasPrice` method in `GnoProvider` to query gas price directly from chain
- Update gas price constants and calculation logic
- Simplify gas price related interfaces and remove unnecessary complexity
- Remove indexer-based gas price fetching
- Added new ABCI query endpoint for gas price
- Implemented gas price parsing from chain response
- Updated gas price calculation with new base values
- Simplified `ITransactionGasRepository` interface
- Removed `GasPriceTierInfo` type

feat: query gas price from chain

---

packages/adena-extension/src/pages/popup/wallet/nft-transfer-summary/index.tsx
packages/adena-extension/src/pages/popup/wallet/transfer-summary/index.tsx

- bug
This PR addresses an issue where transactions could be broadcasted before properly calculating and validating gas fees. The changes improve the gas fee calculation logic and prevent transaction broadcasting when there are insufficient funds.
- Added proper balance validation before transaction broadcasting
- Improved error handling for network fee validation

fix: handle broadcast transaction before calculating gas fee

---

packages/adena-extension/src/pages/popup/certify/login/index.tsx
packages/adena-extension/src/pages/popup/wallet/approve-login/index.tsx

- bug
This PR improves the login functionality by disabling the login button when the password field is empty. This change enhances both user experience and security by preventing unnecessary login attempts.
- Added `availableLogin` state to track password validity
- Disabled login button when password is empty
- Added additional validation check before login attempt
- Applied changes to both main login and approve login pages
- Added `disabled` prop to Button component
- Implemented early return in login functions when password is empty

fix: disable login button when empty string

---

packages/adena-extension/src/resources/chains/chains.json
packages/adena-extension/src/resources/faucet/faucet-api.json

- chore
This PR updates the network configuration to use the staging environment instead of portal-loop. This change affects both the chain configuration and faucet API endpoints.
- Updated chain configuration in `chains.json`:
- Changed chain ID from `portal-loop` to `staging`
- Updated network ID and name
- Maintained other chain parameters (RPC URL, indexer URL, etc.)
- Updated faucet API configuration in `faucet-api.json`:
- Changed faucet endpoint mapping from `portal-loop` to `staging`
- Chain Configuration Changes:
- `id`: portal-loop → staging
- `chainId`: portal-loop → staging
- `networkId`: portal-loop → staging
- `networkName`: Portal Loop → Staging
- Faucet API Changes:
- Updated endpoint mapping for staging environment

chore: change the portal-loop to staging

---

packages/adena-extension/package.json
packages/adena-extension/src/common/validation/validation-message.ts
packages/adena-extension/src/components/molecules/approve-transaction-message-box/approve-transaction-message-box.tsx
packages/adena-extension/src/components/molecules/approve-transaction-message/approve-transaction-message.spec.tsx
packages/adena-extension/src/inject/message/command-handler.ts
packages/adena-extension/src/inject/message/methods/gno-connect.ts
packages/adena-extension/src/migrates/migrations/v011/storage-migration-v011.spec.ts
packages/adena-extension/src/migrates/migrations/v011/storage-migration-v011.ts
packages/adena-extension/src/repositories/transaction/response/transaction-history-query-response.ts
packages/adena-extension/src/resources/chains/chains.json
packages/adena-module/package.json
packages/adena-module/src/libs/gno-js-client/proto/gno/vm.ts
packages/adena-module/src/utils/messages.ts
yarn.lock

- chore
This PR updates the `@gnolang/gno-js-client` dependency from version 1.3.2 to 1.4.1 and implements support for the new `max_deposit` field across the Adena wallet codebase.
- **@gnolang/gno-js-client**: 1.3.2 → 1.4.1
- **@adena-wallet/sdk**: 0.0.2 → 0.0.10
- Added `max_deposit` field support to transaction message types
- Updated proto message handlers for MsgCall, MsgAddPackage, and MsgRun
- Enhanced transaction parsing to include max_deposit information
- Updated type definitions and interfaces across the codebase
- **MsgCallValue**: Added `max_deposit` field
- **MsgRunValue**: Added `max_deposit` field  
- **AddPackageValue**: Added `max_deposit` field and updated structure
- **GnoMessageInfo**: Added `maxDeposit` property
- Updated proto message encoding/decoding for deposit …

chore: update gno-js-client with deposit column

---

packages/adena-extension/src/common/constants/url.constant.ts
packages/adena-extension/src/inject/message/methods/gno-connect.spec.ts
packages/adena-extension/src/inject/message/methods/gno-connect.ts

- bug
- Apply decodeURIComponent to all transaction arguments to correctly decode URL-encoded values
- Add tests for different URL encoding cases
- https://github.com/onbloc/adena-wallet/issues/732
- https://github.com/onbloc/adena-wallet/issues/758
- [BUG] Decode txlink parameters within the wallet

fix: tx-link decode
